#ifndef UTIL_COMM_H
#define UTIL_COMM_H

#define UTIL_COMM_VERSION_MAJOR 2
#define UTIL_COMM_VERSION_MID 0
#define UTIL_COMM_VERSION_MINOR 3


#define UTIL_COMM_MAGIC { 0x55, 0xAA }

enum command {
    UTIL_COMM_GET_VERSION = 0x11,
    UTIL_COMM_ENTER_BOOTLOADER,
    UTIL_COMM_DISABLE_KEYBOARD,
    UTIL_COMM_ENABLE_KEYBOARD,
    UTIL_COMM_GET_KEYSTATE,
    UTIL_COMM_GET_THRESHOLDS,
    UTIL_COMM_GET_KEYBOARD_FILENAME,
    UTIL_COMM_ERASE_EEPROM,
    UTIL_COMM_GET_SIGNAL_VALUE,
    UTIL_COMM_GET_KEYBOARD_DETAILS,
    UTIL_COMM_SHIFT_DATA,
};

enum response {
    UTIL_COMM_RESPONSE_OK = 0x22,
    UTIL_COMM_RESPONSE_ERROR
};

#endif
